apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      # port to hit the service ip on
      port: 8080
      # port your pod app is running on
      targetPort: 80
