apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studentportal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhileshmishrabiz/k8sbootcamp-march26
    targetRevision: main
    path: day3/k8s/argo-app/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true