apiVersion: v1
kind: Namespace
metadata:
  name: week3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-dep
  namespace: week3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: docker.io/library/nginx:latest
        ports:
        - containerPort: 80
