---
name: 3tier k8s build & deploy

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 879381241087.dkr.ecr.ap-south-1.amazonaws.com
  # environment_branch: prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: frontend
            ecr_repo: devopsdozo-frontend
            path: k8s-3-tier-app/app/frontend/
          - name: backend
            ecr_repo: devopsdozo-backend
            path: k8s-3-tier-app/app/backend/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
           #### if using aws access keys and secrets
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-region: ${{ env.AWS_REGION }}

          #### if using aws role to assume - OIDC
          role-to-assume: arn:aws:iam::879381241087:role/GitHubActionsECSDeployRole
          role-session-name: GitHub_to_AWS_OIDC_3tier
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build ${{ matrix.service.name }}
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}/${{ matrix.service.ecr_repo }}:${{ github.sha }} ${{ matrix.service.path}}


      - name: Push ${{ matrix.service.name }}
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ matrix.service.ecr_repo }}:${{ github.sha }}



 

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         # repository: akhileshmishrabiz/k8s-bootcamp-dec25
  #         ref: prod
  #         # token: ${{ secrets.GITHUB_TOKEN }}


  #     - name: Update Kubernetes deployment manifest
  #       run: |

  #         # Update the image in the deployment file
  #         sed -i "s|image:.*${{ matrix.service.name }}.*|image: ${{ env.ECR_REGISTRY }}/${{ matrix.service.ecr_repo }}:${{ github.sha }}|g" \
  #           ./${{ env.menifest_path }}/${{ matrix.service.menifest }}

  #         echo "Updated ${{ matrix.service.menifest }} with new image tag -> ${{ github.sha }}"
  #         echo "Image: ${{ env.ECR_REGISTRY }}/${{ matrix.service.ecr_repo }}:${{ github.sha }}"

  #     - name: Commit and push updated manifests
  #       run: |
  #         git config --global user.name "github-actions[bot]"
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git add ${{ env.menifest_path }}/*.yaml
  #         git diff --staged --quiet || git commit -m "Update ${{ matrix.service.name }} image to ${{ github.sha }} tag"
  #         git pull --rebase origin ${{ env.environment_branch }}
  #         git push --force origin ${{ env.environment_branch }}

  #     - name: Summary
  #       run: |
  #         echo " Built and pushed ${{ matrix.service.name }}" >> $GITHUB_STEP_SUMMARY
  #         echo "Image: ${{ env.ECR_REGISTRY }}/${{ matrix.service.ecr_repo }}:${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
  #         echo "Updated deployment manifest with new image" >> $GITHUB_STEP_SUMMARY