name: 3tier-build-deploy-k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  tag: $GITHUB_SHA
  

jobs:
  build-services:
    runs-on: ubuntu-latest

  env:
    frontend_ecr_repo: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/devopsdozo-frontend
    path_frontend: k8s-3-tier-app/app/frontend/
    backend_ecr_repo0: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/devopsdozo-backend
    path_backend: k8s-3-tier-app/app/backend/ 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: setup docker

      - name: Build backend
        run: |
        # 
        docker build -t ${{ env.backend_ecr_repo0 }}:${{ env.tag }} ${{ env.path_backend }}




      




        